# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Push Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Setup GitVersion
      run: dotnet tool install GitVersion.Tool --global --add-source https://api.nuget.org/v3/index.json
    - name: RunGitVersion
      working-directory: ./src/Bdziam.ExternalDependencyResolver
      run: dotnet-gitversion /updateprojectfiles /showconfig /config ../../GitVersion.yml
    - name: Publish Package
      uses: Jacup/publish-nuget@v2.6.0
      with:
        PROJECT_FILE_PATH: ./src/Bdziam.ExternalDependencyResolver/Bdziam.ExternalDependencyResolver.csproj"
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_PUSHKEY}}
